### PR TITLE
Download pybind11 via CMake instead of shipping it

### PR DESCRIPTION
**Pull request by volkm**
Download pybind11 in the configure step such that it is available for `add_subdirectory`.
Should best be merged simultaneous to the similar PR in pycarl https://github.com/moves-rwth/pycarl/pull/15/.

### CODE REVIEW

**Comment by volkm** [comment]
Will also update pybind to version 2.10.0 and should fix #68.

**Comment by sjunges** [comment]
I think that ultimately, it would be good if we could set the pybind version as an option. That way, if someone depends on a particular pybind version, it is easier to fix. Not urgent though. 

Otherwise: LGTM and many thanks

**Comment by volkm** [comment]
One can already define the version in `include_pybind11.cmake`. Setting it in CMake and from Python `setup.py` should be easy to implement. Setting the version should however be an expert option, because pybind updates might require code adaptions.

**Comment by sjunges** [comment]
As it currently must be the same as pycarls version, does it make sense to take the pycarl version as default?

**Comment by volkm** [comment]
The recent changes allow to set the pybind version to use. As default we are using the pybind version exported by pycarl (see https://github.com/moves-rwth/pycarl/pull/15). Note that this requires to import pycarl during the build process and pycarl was added to `setup_requires`.

**Comment by volkm** [comment]
Tests are currently failing, because https://github.com/moves-rwth/pycarl/pull/15 is not used yet.

**Comment by sjunges** [comment]
LGTM

**Pull request merged**
