### PR TITLE
Adaption to changes in Storm

### PR DESCRIPTION
**Pull request by volkm**
Tests failed due to changes in https://github.com/moves-rwth/storm/pull/556

### CODE REVIEW

**Comment by sjunges** [comment]
Many thanks! LGTM. But should there be a default argument here?

**Comment by volkm** [comment]
The original Storm methods do not have a default either. Is `true` as sensible default value?

**Comment by sjunges** [comment]
Probably it is but if the C++ methods do not have a default, then it is maybe good to not introduce one here right now :-)

**Comment by volkm** [comment]
Then I will keep it unchanged for now.

**Pull request merged**
