### PR TITLE
Update changed namespaces in Storm

### PR DESCRIPTION
**Pull request by TheGreatfpmK**
Pull request https://github.com/moves-rwth/storm/pull/644 in Storm broke the build of StormPy because some namespaces were changed.

### CODE REVIEW

**Comment by sjunges** [comment]
Thanks! This fixes some, but not all introduced problems... @volkm  Shall we merge it now?

**Comment by volkm** [comment]
Let me quickly go over it and add the remaining namespace changes.

**Comment by TheGreatfpmK** [comment]
Sorry if there was more than this, I was compiling Storm today and this popped up

**Comment by volkm** [comment]
These should be all changes. I will merge it if the CI was successful.

Thanks for the fixes!

**Comment by volkm** [comment]
Running the CI with the updated Storm images is now successful and we can merge it.

**Pull request merged**
