### PR TITLE
Add bindings for the Smg class

### PR DESCRIPTION
**Pull request by TheGreatfpmK**
Added all the needed bindings for the Smg class.

Also fixed SparseModelComponents binding wrong property as 'player1_matrix'.

### CODE REVIEW

**Comment by sjunges** [comment]
LGTM. Is there a way to create an SMG inside stormpy, e.g., via the components? Would be great if you could add a small test case for this to ensure that we do not break things in the future.  (Maybe in tests/storage/...)?

**Comment by TheGreatfpmK** [comment]
I haven't tried building the model in StormPy, but I will take a look! I will also add a test.

**Comment by TheGreatfpmK** [comment]
I added a small test case for constructing SMG from sparse model components!

**Comment by sjunges** [comment]
Great. Once the tests finish, I will merge it!

**Pull request merged**
