### PR TITLE
Replaced deprecated distutils.Version

### LINKED ISSUE #93: Deprecation warning
I get the following warning when running stormpy on python 3.9.x

```
/Users/junges/stormpy/setup.py:80: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(storm_version) < StrictVersion(storm_min_version):
```

### PR DESCRIPTION
**Pull request by volkm**
Fix #93

### CODE REVIEW

**Comment by sjunges** [comment]
That was quick... Is this a solution for older python versions? Do we need to be careful?

**Comment by volkm** [comment]
... and it fails. I should add the package as requirement.

To answer your question: `packaging` requires at least Python 3.7. Ubuntu 18.04 comes with Python 3.6. So we might need a distinction for older Python versions.

**Comment by sjunges** [comment]
I think we should ditch 18.04. I dont want to write additional code for versions that old...

**Comment by volkm** [comment]
We require at least Python version 3.7 now. The Storm Docker containers are all based on Ubuntu 22.04, so the tests should be fine.

**Comment by sjunges** [comment]
LGTM

**Pull request merged**
